title:  "Tibor Jager"
description: ""
logo: Web2.jpg
show_downloads: false

<<<<<<< HEAD
theme: jekyll-theme-hacker
=======
theme: jekyll-theme-minimal
>>>>>>> 1768605a071944fb0fb7fbb4c78b2d7ae72d116d
